package main

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/sosedoff/gitkit"
)

type pluginManifest struct {
	Name        string             `json:"name"`
	Description string             `json:"description,omitempty"`
	Version     string             `json:"version,omitempty"`
	Author      *marketplaceAuthor `json:"author,omitempty"`
	Homepage    string             `json:"homepage,omitempty"`
	License     string             `json:"license,omitempty"`
}

func (a *App) repoPath(name string) string {
	return filepath.Join(a.cfg.DataDir, "repos", name+".git")
}

func (a *App) workPath(name string) string {
	return filepath.Join(a.cfg.DataDir, "work", name)
}

func runGit(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	if dir != "" {
		cmd.Dir = dir
	}
	cmd.Env = append(os.Environ(),
		"GIT_AUTHOR_NAME=marketplace",
		"GIT_AUTHOR_EMAIL=marketplace@local",
		"GIT_COMMITTER_NAME=marketplace",
		"GIT_COMMITTER_EMAIL=marketplace@local",
	)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return string(out), fmt.Errorf("git %s: %w: %s", strings.Join(args, " "), err, string(out))
	}
	return string(out), nil
}

func (a *App) ensureBareRepo(name string) error {
	bare := a.repoPath(name)
	if _, err := os.Stat(filepath.Join(bare, "HEAD")); err == nil {
		return nil
	}
	if err := os.MkdirAll(bare, 0o755); err != nil {
		return err
	}
	if _, err := runGit("", "init", "--bare", "-b", "main", bare); err != nil {
		return err
	}
	if _, err := runGit(bare, "config", "http.receivepack", "false"); err != nil {
		return err
	}
	if _, err := runGit(bare, "config", "http.uploadpack", "true"); err != nil {
		return err
	}
	return nil
}

func (a *App) ensureWorkTree(name string) error {
	work := a.workPath(name)
	bare := a.repoPath(name)
	if _, err := os.Stat(filepath.Join(work, ".git")); err == nil {
		return nil
	}
	if err := os.MkdirAll(work, 0o755); err != nil {
		return err
	}
	if _, err := runGit(work, "init", "-b", "main"); err != nil {
		return err
	}
	if _, err := runGit(work, "remote", "add", "origin", bare); err != nil {
		return err
	}
	return nil
}

func (a *App) removeRepo(name string) {
	os.RemoveAll(a.repoPath(name))
	os.RemoveAll(a.workPath(name))
}

func (a *App) materializePlugin(ctx context.Context, p *Plugin) error {
	if err := a.ensureBareRepo(p.Name); err != nil {
		return err
	}
	if err := a.ensureWorkTree(p.Name); err != nil {
		return err
	}
	work := a.workPath(p.Name)

	if err := wipeWorkTree(work); err != nil {
		return err
	}

	manifestDir := filepath.Join(work, ".claude-plugin")
	if err := os.MkdirAll(manifestDir, 0o755); err != nil {
		return err
	}
	manifest := pluginManifest{
		Name:        p.Name,
		Description: p.Description,
		Version:     p.Version,
		Homepage:    p.Homepage,
		License:     p.License,
	}
	if p.AuthorName != "" || p.AuthorEmail != "" {
		manifest.Author = &marketplaceAuthor{Name: p.AuthorName, Email: p.AuthorEmail}
	}
	mb, _ := json.MarshalIndent(manifest, "", "  ")
	if err := os.WriteFile(filepath.Join(manifestDir, "plugin.json"), append(mb, '\n'), 0o644); err != nil {
		return err
	}

	skills, err := a.loadSkillsForPlugin(ctx, p.ID)
	if err != nil {
		return err
	}
	if len(skills) > 0 {
		skillsRoot := filepath.Join(work, "skills")
		if err := os.MkdirAll(skillsRoot, 0o755); err != nil {
			return err
		}
		for _, s := range skills {
			dir := filepath.Join(skillsRoot, s.Name)
			if err := os.MkdirAll(dir, 0o755); err != nil {
				return err
			}
			content := buildSkillMarkdown(s)
			if err := os.WriteFile(filepath.Join(dir, "SKILL.md"), []byte(content), 0o644); err != nil {
				return err
			}
			files, err := a.loadSkillFiles(ctx, s.ID)
			if err != nil {
				return err
			}
			for _, f := range files {
				if err := writeSkillFileToWorkTree(dir, f); err != nil {
					return err
				}
			}
		}
	}

	readme := fmt.Sprintf("# %s\n\n%s\n\nGenerated by self-hosted marketplace.\n", p.Name, p.Description)
	if err := os.WriteFile(filepath.Join(work, "README.md"), []byte(readme), 0o644); err != nil {
		return err
	}

	if _, err := runGit(work, "add", "-A"); err != nil {
		return err
	}
	out, err := runGit(work, "status", "--porcelain")
	if err != nil {
		return err
	}
	if strings.TrimSpace(out) == "" {
		return nil
	}
	if _, err := runGit(work, "commit", "-m", "Update plugin contents"); err != nil {
		return err
	}
	if _, err := runGit(work, "push", "origin", "HEAD:refs/heads/main", "--force"); err != nil {
		return err
	}
	return nil
}

func wipeWorkTree(work string) error {
	entries, err := os.ReadDir(work)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.Name() == ".git" {
			continue
		}
		if err := os.RemoveAll(filepath.Join(work, e.Name())); err != nil {
			return err
		}
	}
	return nil
}

// writeSkillFileToWorkTree decodes a SkillFile (text or base64-binary) and
// writes it under skillDir at its relative path, creating intermediate dirs
// as needed. Path safety has already been enforced at upload time, but we
// re-anchor under skillDir here as a defence in depth.
func writeSkillFileToWorkTree(skillDir string, f SkillFile) error {
	rel := filepath.FromSlash(f.Path)
	full := filepath.Join(skillDir, rel)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		return err
	}
	var data []byte
	if f.IsBinary {
		decoded, err := base64.StdEncoding.DecodeString(f.Content)
		if err != nil {
			return fmt.Errorf("decode %s: %w", f.Path, err)
		}
		data = decoded
	} else {
		data = []byte(f.Content)
	}
	return os.WriteFile(full, data, 0o644)
}

func buildSkillMarkdown(s Skill) string {
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("name: " + s.Name + "\n")
	desc := strings.ReplaceAll(s.Description, "\n", " ")
	b.WriteString("description: " + desc + "\n")
	b.WriteString("---\n\n")
	body := s.Body
	if body == "" {
		body = "## " + s.Name + "\n\n" + s.Description + "\n"
	}
	if !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	b.WriteString(body)
	return b.String()
}

func (a *App) gitHandler() http.Handler {
	reposDir := filepath.Join(a.cfg.DataDir, "repos")
	service := gitkit.New(gitkit.Config{
		Dir:        reposDir,
		AutoCreate: false,
		Auth:       false,
	})
	if err := service.Setup(); err != nil {
		panic(fmt.Sprintf("gitkit setup: %v", err))
	}
	return http.StripPrefix("/git", service)
}
